
srv_port: &srv_port 1123
max_size: 1024

replicaCount: 1

image:
  repository: key-server
  tag: "latest"
  pullPolicy: Never

service:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http

livenessProbe:
  tcpSocket:
    port: *srv_port
  initialDelaySeconds: 5
  periodSeconds: 15

readinessProbe:
  httpGet:
    path: /metrics
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5

env: []

resources: 
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 200m
    memory: 128Mi
